[environments]
NIXPACKS_BUILD_LANGUAGE = "php"

[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"

[deploy]
startCommand = "php artisan serve --port=$PORT"
postDeployCommand = "php artisan migrate --force && php artisan db:seed --force"